### PR TITLE
Bob vapor template

### PR DESCRIPTION
**Pull request by JanC**
Hi 👋 
I created a vapor template to make the installation of Bob easier. It requires swift-tools-version:4.0 though

```
vapor new BobTheBuilder tamplate=n26/bob-vapor-template
```

### CODE REVIEW

**Review by i-dama — CHANGES_REQUESTED** [review]
I don't feel comfortable pointing the template to another repository. Could we include the template into this one?

**Comment by JanC** [comment]
That was my initial intention but it looks like the templates must be at the root of a repo. I can transfer it to N26 if you want

**Comment by i-dama** [comment]
Let me look into it and get back to you :)

**Comment by i-dama** [comment]
@JanC Thanks for having the patience. I finally had a deeper look. This looks awesome, let me get another repo going for the template. 
I'll ping you as soon as it's up

**Comment by i-dama** [comment]
@JanC the repo is up!
https://github.com/n26/bob-vapor-template

Could you make a PR there with the template? Than we can update this PR to point there

**Comment by JanC** [comment]
sure, the n26/bob-vapor-template is currently empty so I cannot fork it to create a PR though

**Comment by i-dama** [comment]
Better now?

**Comment by JanC** [comment]
nope :)
screenshot 2018-10-25 at 17 50 17

**Comment by i-dama** [comment]
image
Alright, now it should be good :D

**Review by i-dama — APPROVED** [review]

**Comment by i-dama** [comment]
I'll merge this as soon as we have the template up :)
I don't want someone to try the instructions only to see them fail

**Comment by i-dama** [comment]
🎉  Thanks for your contribution!

**Pull request merged**
